chat:
  globalSymbol: "!"
  localChatRadius: 128

  formats:
    global: "%luckperms_prefix%<gray><player><reset>%ccb_tag%<gray>: <white><message>"
    local: "%luckperms_prefix%<gray><player><reset>%ccb_tag%<gray>: <gray><message>"
    clan: "%luckperms_prefix%<dark_green><player><reset>%ccb_tag%<gray>: <green><message>"

  adminChat:
    symbol: "#"
    permission: "zovchat.adminChat"
    format: "%luckperms_prefix%<dark_red><player><reset>%ccb_tag%<gray>: <red><message>"

mention:
  color: "<gold>"

database:
  name: "database.db"
  poolSize: 1
