chat:
  globalSymbol: "!"
  localChatRadius: 128

  formats:
    global: "%luckperms_prefix%<gray><player><reset>%ccb_tag%<gray>: <white><message>"
    local: "%luckperms_prefix%<gray><player><reset>%ccb_tag%<gray>: <gray><message>"

mention:
  color: "<gold>"

database: 
  url: "database.db"
  poolSize: 10
