name: ZovChat
version: "1.0"
main: dev.hxragi.chat.ZovChat
description: ZOV SVO RUSSIA THE BEST
api-version: "1.21.11"
loader: dev.hxragi.chat.ZovChatLoader

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
